---
title: "Practical3"
author: '2140365'
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r loadData, echo=FALSE}
library(rio)
library(dplyr)
Comp_Data <- import("indicator_hour compensation.xlsx", setclass = "tibble")
colnames(Comp_Data) <- c("country", 1980:2006)
library(knitr)
Country_Matrix <- matrix(c(Comp_Data$country,""),5,7)
kable(t(Country_Matrix), table.attr = "style='width:80%;'", 
      caption="Countries represented in the data set")
```


```{r tidyr, echo=FALSE}
library(tidyr)
Tidy_Data <- gather(Comp_Data, key = 'year', value = 'compensation', -country)
head(Tidy_Data,5)

Tidy_Data <- Tidy_Data%>%
  mutate(country = factor(country), year = as.numeric(year)) %>%
  arrange(country) %>%
  na.omit
```


```{r subData_Singapo, echo=FALSE}
# Select relevant subset of data
Sub_Data_Sing <- filter(Tidy_Data, (country == "Singapore") & 
                     (year %in% c(1980,1985,1990,1995,2000,2005)))
# Produce a scatterplot
library(ggplot2)
ggplot(Sub_Data_Sing, aes(x = factor(year), y = compensation)) + geom_point()
```


```{r subData_Austra, echo=FALSE,out.width="50%",fig.width=6,fig.asp=0.618}
sub_Data_Aus <- filter(Tidy_Data, (country == "Australia") &
                         (year %in% c(1980,1990,2000,2005)))

ggplot(sub_Data_Aus, aes(x = factor(year), y = compensation)) +
    geom_bar(stat = "identity", fill = "lightblue") + 
    ggtitle("Hourly compensation in Australia has risen substantially.") 

ggplot(sub_Data_Aus, aes(x = factor(year), y = compensation, fill = factor(year))) +
    geom_bar(colour = "black",  stat = "identity") +
    scale_fill_manual(values = c("steelblue", "steelblue", "steelblue", "red")) + 
   labs(x = "Year", y = "Hourly compensation cost", 
         title = "Hourly compensation in Australia has risen substantially.")+
  guides(fill = FALSE)

```


```{r compare2Contries, echo=FALSE}
Sub_Data_Aus_UK <- filter(Tidy_Data, (country %in% c("Australia","United Kingdom")) 
                   & (year %in% c(1980,1990,2000)))
# Grouped boxplot
ggplot(Sub_Data_Aus_UK, aes(x = factor(year), y = compensation, fill = country)) +
    geom_bar(colour = "black", position = "dodge", stat = "identity") +
    labs(x = "Year", y = "Hourly compensation cost", 
         title = "British hourly cost overtakes Australian hourly cost.",
         subtitle = "Data source: www.gapminder.org") 
```


```{r yearData, echo=FALSE}

sub_Data_year <- filter(Tidy_Data, year %in% c(1980,1990,2000,2005))

ggplot(sub_Data_year, aes(x = factor(year), y = compensation, fill = factor(year))) + 
  geom_violin(scale = "count") + geom_jitter(height = 0, width = 0.05) +
  guides(fill = FALSE) + labs(x = "Year", y = "Hourly compensation cost",
                              subtitle = "Data source: www.gapminder.org")

```


```{r lines, echo=FALSE}
myplot <- ggplot(Tidy_Data, aes(x = year, y = compensation, group = country)) + 
  geom_line() + labs( x = "Year", y = "Hourly compensation cost", 
                       subtitle = "Data source: www.gapminder.org") + 
  geom_smooth(colour = "green", method = "loess", group = 1)
print(myplot)
```


```{r joinCountries, echo=FALSE}
Countries <- import("Countries.xlsx", setclass = "tibble")
Countries <- filter(Countries, country %in% Tidy_Data$country)
# Join the data frames and implement categorical data as factors
Tidy_Data <- left_join(Tidy_Data, Countries, by = "country")
Tidy_Data <- mutate(Tidy_Data, country = factor(country), 
                    continent = factor(continent))
```


```{r numOfCountries,echo=FALSE}
library(knitr)
kable(t(as.matrix(summary(filter(Tidy_Data, year == 2005)$continent))), 
      align = c('r', 'r', 'r', 'r', 'r'))
```


```{r compareAsianEurpoe}
Sub_Data <- filter(Tidy_Data, continent %in% c("Asia", "Europe"))
ggplot(Sub_Data, aes(x = year, y = compensation, group = country)) + 
  geom_line() +  labs( x = "Year", y = "Hourly compensation cost", 
                       subtitle = "Data source: www.gapminder.org") + 
  geom_smooth(se = FALSE, colour = "green", method = "loess", group = 1) +
  facet_wrap( ~ continent)
```


```{r europeTrend, echo=FALSE}

ggplot(filter(Sub_Data, continent == "Europe"), 
       aes(x = year, y = compensation, group = country)) +  
  geom_line() +  labs( x = "Year", y = "Hourly compensation cost", 
                       subtitle = "Data source: www.gapminder.org") + 
  geom_smooth(se = FALSE, colour = "green", method="loess", group=1) +
  annotate("rect", xmin = 1995, xmax = 2002, ymin = 0, ymax = 40, alpha = .1, 
           fill="blue")

```


```{r Asian,echo=FALSE}
Sub_Data <- filter(Tidy_Data, continent == "Asia")
ggplot(Sub_Data, aes(x = year, y = compensation)) + 
  labs( x = "Year", y = "Hourly compensation cost", 
                       subtitle = "Data source: www.gapminder.org") +
  scale_colour_brewer(palette = "Set1") + geom_line() + 
  aes(colour = country) 
```


